[package]
name = "tzo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
serde_json = "1.0.64"
enum-display-derive = "0.1.1"
rand = "0.8.4"